env:
  node: true
  es2021: true
extends:
  - eslint:recommended
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - never
  arrow-parens:
    - error
    - as-needed
  no-trailing-spaces: error
